name: earth_obs_seg2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - gdal # low level library for remote sensing imagery
  - rasterio # python wrapper on top of gdal for visualizing geospatial data
  - pip:
    - segmentation-models-pytorch # includes collection of good segmentation models